default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: idea_desh_development

test:
  <<: *default
  database: idea_desh_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5
  cache:
    <<: *primary_production
    database: idea_desh_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: idea_desh_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: idea_desh_production_cable
    migrations_paths: db/cable_migrate
